-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 11:12:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `lastLogin` DATETIME NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`key` (
  `idkey` VARCHAR(255) NOT NULL,
  `expirationDate` DATETIME NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idkey`),
  INDEX `fk_key_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_key_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `category` TINYINT UNSIGNED NULL,
  `title` VARCHAR(100) NOT NULL,
  `text` TEXT NULL,
  `lastUpdate` DATETIME NOT NULL,
  PRIMARY KEY (`idarticle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `idmedia` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `url` VARCHAR(255) NULL,
  `legend` VARCHAR(100) NULL,
  `thumbnailName` VARCHAR(45) NOT NULL,
  `sourceName` VARCHAR(45) NULL,
  `article_idarticle` INT NOT NULL,
  PRIMARY KEY (`idmedia`),
  INDEX `fk_media_article1_idx` (`article_idarticle` ASC),
  CONSTRAINT `fk_media_article1`
    FOREIGN KEY (`article_idarticle`)
    REFERENCES `mydb`.`article` (`idarticle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `idcategory` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`article_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article_has_category` (
  `article_idarticle` INT NOT NULL,
  `category_idcategory` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`article_idarticle`, `category_idcategory`),
  INDEX `fk_article_has_category_category1_idx` (`category_idcategory` ASC),
  INDEX `fk_article_has_category_article1_idx` (`article_idarticle` ASC),
  CONSTRAINT `fk_article_has_category_article1`
    FOREIGN KEY (`article_idarticle`)
    REFERENCES `mydb`.`article` (`idarticle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_article_has_category_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `mydb`.`category` (`idcategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
